name: push versioned image to aliyun

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Pull image with the same tag and make a tag
        run: |
          docker pull eceasy/cli-proxy-api:${{ steps.get_tag.outputs.TAG }}
          docker tag eceasy/cli-proxy-api:${{ steps.get_tag.outputs.TAG }} registry.cn-shanghai.aliyuncs.com/aliyunwsc/cli-proxy-api:${{ steps.get_tag.outputs.TAG }}

      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v4
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USER }}
          password: ${{ secrets.ALIYUN_DOCKER_PAT }}

      - name: push the image
        run: docker push registry.cn-shanghai.aliyuncs.com/aliyunwsc/cli-proxy-api:${{ steps.get_tag.outputs.TAG }}

      - name: clean the images
        run: docker rmi registry.cn-shanghai.aliyuncs.com/aliyunwsc/cli-proxy-api:${{ steps.get_tag.outputs.TAG }} eceasy/cli-proxy-api:${{ steps.get_tag.outputs.TAG }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # 默认 SSH 端口，如有变化请修改
          script: |
            cd /opt/module/cli-proxy-api
            docker compose down
            MY_IMAGE=registry.cn-shanghai.aliyuncs.com/aliyunwsc/cli-proxy-api:${{ steps.get_tag.outputs.TAG }} docker compose up -d
